Update README.md
minvws/generiekefuncties-adressering pull request #97
Opened 2024-03-20 09:52 UTC by MLHoekstra

2024-03-20 13:43 UTC, stevenvegt requested changes
Linkje fixen en nog wat kleine dingetjes.

2024-03-20 13:43 UTC, stevenvegt commented on README.md
> +Github werkt net even wat anders dan bijvoorbeeld Office 365 of Google docs. We hebben daarom verschillende handleidingen opgesteld
Deze link klopt niet.
Een link zonder tekst kan gewoon zo: `http://example.com/path` en resulteert in http://example.com/path
Een link met tekst kan zo: `[tekst over de link](http://example.com/path)` en resulteert in [tekst over de link](http://example.com/path)

Hier staat de link tussen haakjes en daarna nog een keer zonder.

2024-03-20 13:43 UTC, stevenvegt commented on README.md
> +Github is een omgeving waarin mensen samen kunnen werken. Github wordt veel gebruikt in de ICT en vraagt wat gewenning. Het programma Implementatie generieke functies van het Ministerie van VWS gebru
Ik zou deze zin:
> Github wordt veel gebruikt in de ICT en vraagt wat gewenning

er uit laten. Lijkt me niet relevant voor de introductie.

2024-03-20 13:43 UTC, stevenvegt commented on README.md
> +Niet werkgroepleden zijn uitgenodigd om rond te kijken  en indien je input wilt geven kun je dit doen middels comments.
> kijken en indien

Staat hier een extra spatie of tab tussen?

2024-03-21 13:50 UTC, MLHoekstra commented on README.md
> +Github is een omgeving waarin mensen samen kunnen werken. Github wordt veel gebruikt in de ICT en vraagt wat gewenning. Het programma Implementatie generieke functies van het Ministerie van VWS gebru
akkoord

2024-03-21 13:50 UTC, MLHoekstra commented on README.md
> +Niet werkgroepleden zijn uitgenodigd om rond te kijken  en indien je input wilt geven kun je dit doen middels comments.
verwijderd

2024-03-21 13:50 UTC, MLHoekstra commented on README.md
> +Github werkt net even wat anders dan bijvoorbeeld Office 365 of Google docs. We hebben daarom verschillende handleidingen opgesteld
aangepast

2024-03-22 13:40 UTC, stevenvegt approved these changes

2024-03-22 13:40 UTC, merged